#pragma once
#define IOCTL_BASECODE    0x880
#define MY_CTL_CODE(i) \
    CTL_CODE(FILE_DEVICE_UNKNOWN, IOCTL_BASECODE+i, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ADD_PATH    MY_CTL_CODE(1)
#define IOCTL_DELETE_PATH    MY_CTL_CODE(2)

typedef struct _RULE_NODE 
{
	wchar_t path[260];
	LIST_ENTRY list_Entry;
}RULENODE,*PRULENODE;